// automatically generated by the FlatBuffers compiler, do not modify

package com.julia.Eyetracking.FlatBufferSchema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Message extends Table {
  public static Message getRootAsMessage(ByteBuffer _bb) { return getRootAsMessage(_bb, new Message()); }
  public static Message getRootAsMessage(ByteBuffer _bb, Message obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Message __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String UniqueId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer UniqueIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer UniqueIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public boolean ID() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public Timestamp Timestamp() { return Timestamp(new Timestamp()); }
  public Timestamp Timestamp(Timestamp obj) { int o = __offset(8); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public float Confidence() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float NormalizedPosX() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float NormalizedPosY() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public int PupilDiameter() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static void startMessage(FlatBufferBuilder builder) { builder.startObject(7); }
  public static void addUniqueId(FlatBufferBuilder builder, int UniqueIdOffset) { builder.addOffset(0, UniqueIdOffset, 0); }
  public static void addID(FlatBufferBuilder builder, boolean ID) { builder.addBoolean(1, ID, false); }
  public static void addTimestamp(FlatBufferBuilder builder, int TimestampOffset) { builder.addStruct(2, TimestampOffset, 0); }
  public static void addConfidence(FlatBufferBuilder builder, float Confidence) { builder.addFloat(3, Confidence, 0.0f); }
  public static void addNormalizedPosX(FlatBufferBuilder builder, float NormalizedPosX) { builder.addFloat(4, NormalizedPosX, 0.0f); }
  public static void addNormalizedPosY(FlatBufferBuilder builder, float NormalizedPosY) { builder.addFloat(5, NormalizedPosY, 0.0f); }
  public static void addPupilDiameter(FlatBufferBuilder builder, int PupilDiameter) { builder.addInt(6, PupilDiameter, 0); }
  public static int endMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

